# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    #xcWorkspacePath: 'Calculator-iOS/Kalculator.xcodeproj/project.xcworkspace'
    xcodeVersion: '9' # Options: 8, 9, 10, default, specifyPath
    packageApp: true
    exportOptions: 'specify' # Optional. Options: auto, plist, specify
    exportMethod: 'ad-hoc' # Required when exportOptions == Specify
    exportTeamId: 1234567890 # Optional
    destinationPlatformOption: 'default' # Optional. Options: default, iOS, tvOS, macOS, custom
    #destinationPlatform: # Optional
    destinationTypeOption: 'simulators' # Optional. Options: simulators, devices
    destinationSimulators: 'iPhone 7' # Optional
    #destinationDevices: # Optional
    #args: # Optional
    #workingDirectory: # Optional
    #useXcpretty: true # Optional
    publishJUnitResults: true
